"""
pycyc.io_utils - plain-text/array I/O helpers, in the format used by the
original filter_profile tool (filters.txt, dynamic_spectrum.txt, profile
files), plus the safely_divide numerical helper.
"""

__all__ = ["safely_divide", "loadArray", "writeArray", "writeProfile", "loadProfile"]

import numpy as np

def safely_divide(numer, denom):
    safe_denom = np.where(denom == 0, 1, denom)
    result = numer / safe_denom
    result[denom == 0] = 0
    return result



def loadArray(fname):
    """
    Load array from txt file in format generated by filter_profile,
    useful for filters.txt, dynamic_spectrum.txt
    """
    fh = open(fname, "r")
    try:
        x = int(fh.readline())
    except Exception:
        raise Exception("couldn't read first dimension")
    try:
        y = int(fh.readline())
    except Exception:
        raise Exception("couldn't read second dimension")
    raw = np.loadtxt(fh)
    if raw.shape[0] != x * y:
        raise Exception(
            "number of rows of data=",
            raw.shape[0],
            " not equal to product of dimensions:",
            x,
            y,
        )
    if len(raw.shape) > 1:
        data = raw[:, 0] + raw[:, 1] * 1j
    else:
        data = raw[:]
    data.shape = (x, y)
    fh.close()
    return data



def writeArray(fname, arr):
    """
    Write array to ascii file in same format as filter_profile does
    """
    fh = open(fname, "w")
    fh.write("%d\n" % arr.shape[0])
    fh.write("%d\n" % arr.shape[1])
    for x in range(arr.shape[0]):
        for y in range(arr.shape[1]):
            if arr.dtype == np.complex128:
                fh.write("%.7e %.7e\n" % (arr[x, y].real, arr[x, y].imag))
            else:
                fh.write("%.7e\n" % (arr[x, y]))
    fh.close()



def writeProfile(fname, prof):
    """
    Write profile to ascii file in same format as filter_profile does
    """
    t = np.linspace(0, 1, prof.shape[0], endpoint=False)
    fh = open(fname, "w")
    for x in range(prof.shape[0]):
        fh.write("%.7e %.7e\n" % (t[x], prof[x]))
    fh.close()



def loadProfile(fname):
    """
    Load profile in format generated by filter_profile
    """
    x = np.loadtxt(fname)
    return x[:, 1]


#
# norm="ortho" is used in the following definitions in order to preserve power
#

